@description('Naam van de Azure Managed Grafana instantie')
param name string

@description('Locatie van de Azure Managed Grafana instantie')
param location string

@description('Generated from /subscriptions/6c516f03-07d2-44c8-8ab5-15d92d64f2f5/resourceGroups/PoC/providers/Microsoft.Dashboard/grafana/PoC-dashboard')
resource grafana 'Microsoft.Dashboard/grafana@2024-10-01' = {
  name: name
  sku: {
    name: 'Essential'
  }
  location: location
  tags: {}
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    zoneRedundancy: 'Disabled'
    publicNetworkAccess: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    apiKey: 'Disabled'
    deterministicOutboundIP: 'Disabled'
    grafanaIntegrations: {
      azureMonitorWorkspaceIntegrations: [] //later toevoegen
    }
    grafanaConfigurations: {
      smtp: {
        enabled: false
      }
    }
    grafanaMajorVersion: '11'
  }
}

output grafanaId string = grafana.id
