name: Deploy Azure PoC Bicep Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check required Bicep files
        run: |
          echo "📦 Verifying Bicep files exist..."
          required_files=(
            "main.bicep"
            "infra/Loganalyticworkspace.bicep"
            "infra/applicationinsights.bicep"
            "infra/keyvault.bicep"
            "infra/storageaccount.bicep"
            "infra/blobservice.bicep"
            "infra/Staticwebsite.bicep"
            "infra/appserviceplan.bicep"
            "infra/appservice.bicep"
            "infra/Managedidentity.bicep"
            "infra/Grafana.bicep"
          )

          for file in "${required_files[@]}"; do
            if [[ ! -f "$file" ]]; then
              echo "❌ ERROR: Missing required file: $file"
              exit 1
            fi
          done
          echo "✅ All required files are present."

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep template to Azure
        run: |
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RG }} \
            --template-file main.bicep
            --parameters @parameters.json
